services:
  - type: web
    name: human-coin-site
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        headers:
          Cache-Control: public, max-age=3600
          X-Content-Type-Options: nosniff
      - path: /bg.mp4
        headers:
          Cache-Control: public, max-age=86400
      - path: /style.css
        headers:
          Cache-Control: public, max-age=86400
      - path: /script.js
        headers:
          Cache-Control: public, max-age=86400
    routes:
      - type: rewrite
        source: /*
        destination: /index.html